name: Update Scholar Stats
on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4  # Updated from v2

    - name: Set up Python
      uses: actions/setup-python@v5  # Updated from v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scholarly

    - name: Update scholar stats
      run: python bin/fetch_scholar_stats.py

    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add asset/data/scholar_stats.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update scholar stats" && git push)

    # Build artifact that will be used for deployment
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'  # Upload the entire repository

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}