# .github/workflows/update_scholar_stats.yml

name: Update Scholar Stats

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3  # Updated to v3
      with:
        fetch-depth: 0  # Fetch all history for proper git operations

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4
      with:
        python-version: '3.10'  # Specify Python version explicitly
        cache: 'pip'  # Enable pip caching

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scholarly requests

    - name: Update scholar stats
      run: |
        # Create directories if they don't exist
        mkdir -p asset/data
        python bin/fetch_scholar_stats.py
      continue-on-error: true  # Continue even if script fails

    - name: Check for changes
      id: check_changes
      run: |
        git add asset/data/scholar_stats.json
        git status --porcelain | grep "asset/data/scholar_stats.json" || echo "no_changes=true" >> $GITHUB_OUTPUT

    - name: Commit and push if changed
      if: steps.check_changes.outputs.no_changes != 'true'
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git commit -m "Update scholar stats [skip ci]"
        git push

    - name: Report status
      if: always()
      run: |
        if [ "${{ steps.check_changes.outputs.no_changes }}" == "true" ]; then
          echo "No changes to commit"
        else
          echo "Changes committed and pushed"
        fi